baseURL: "https://storied-semifreddo-c9040c.netlify.app/"
languageCode: en-us
title: Data Stories by Mahima
theme: PaperMod

params:
  homeInfoParams:
    Title: 'Hello Stranger : )'
    Content: 'Welcome to my blog! In this blog I paint stories with data. 
    As I explore the different facets of data analytics, I want to document them in one place and along 
    the way create a unique space for myself.'
  socialIcons:
      - name: linkedin
        url: 'https://www.linkedin.com/in/mahima-kriti/'
      - name: instagram
        url: 'https://www.instagram.com/the_arana_/'
      - name: github
        url: 'https://github.com/MAHIMAKRITI/'

  ShowBreadcrumbs: true

  ShowReadingTime: true

  ShowShareButtons: true

  ShowPostNavLinks: true


menu:
  main:
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: about
      name: About me
      url: /about/
      weight: 10
